'use strict';
// CP4: import-safe declarations only. No runtime module imports or activation.
// Entry points describe current source; next/requires describe conditional intent,
// not successful existing composition. CP7-CP12 wire and prove those handoffs.
const schema = { path: 'scripts/lib/system/schemas.js', exportName: 'CapabilityHandoffSchema' };
const entry = (path, exportName = null, invocation = 'MODULE') => ({
  path, exportName, invocation, importPolicy: 'DO_NOT_IMPORT_DURING_INVENTORY'
});
const route = entry('scripts/evaluators/route_query.js', 'executeRoutedQuery');
const evaluate = entry('scripts/evaluators/eval_boq.js', 'runEvaluationPipeline');
const next = (capabilityId, when) => ({ capabilityId, when });
const capability = spec => ({
  skillPath: `.agents/skills/${spec.capabilityId}/SKILL.md`,
  kind: 'CUSTOMER', vendorScope: ['HPE'], domainScope: ['EXACT_SUPPORTED_PROFILE'],
  executionMode: 'LOCAL', inputSchema: schema, outputSchema: schema,
  schemaApplicability: 'PROPOSED_HANDOFF_NOT_LEGACY_SIGNATURE', requires: [], next: [],
  tests: ['tests/unit/test_skill_workflow_registry_contracts.js'],
  maintainer: 'Repository lead solution execution architect', ...spec
});

const registry = {
  schemaVersion: 1, activation: 'UNUSED',
  dependencySemantics: 'DECLARED_CONDITIONAL_HANDOFFS_NOT_ACTIVE_DISPATCH',
  capabilities: [
    capability({ capabilityId: 'presales-query-router', intents: ['INTAKE_CLASSIFICATION'],
      triggers: ['Incoming presales query or customer document'],
      applicability: ['Classify objective, modality, scope and requested transforms'],
      executionMode: 'HYBRID', vendorScope: ['EXPLICIT_OR_UNRESOLVED'],
      entrypoints: [route, entry('scripts/evaluators/route_query.js', 'classifyQueryIntent')],
      completionEvidence: ['Intent decision and unresolved scope; real dispatch trace when executed'],
      coverageLimits: ['Legacy keyword router is active; this registry is not a dispatcher. Compound/pre-dispatch gaps remain CP7.'] }),
    capability({ capabilityId: 'boq-eval-skill', intents: ['BOQ_EVALUATION'],
      triggers: ['HPE SKU-based BOQ requiring evaluation'], applicability: ['Exact product catalog and owned components'],
      executionMode: 'HYBRID', entrypoints: [evaluate, entry('scripts/lib/boq/boq_evaluator.js', 'evaluateBOQMultiAspect')],
      completionEvidence: ['Local aspect results, candidate evidence and unresolved checks; exact receipt before acceptance'],
      coverageLimits: ['Local PASS does not certify portal acceptance or complete delivery.'] }),
    capability({ capabilityId: 'multi-cluster-tender-skill', intents: ['MULTI_CLUSTER_TENDER'],
      triggers: ['Multi-node, mixed-cluster or multi-sheet tender'], applicability: ['Owned quantities and explicit node/group scope'],
      entrypoints: [entry('scripts/lib/boq/multi_cluster_splitter.js', 'analyzeAndPartitionClusters'), entry('scripts/evaluators/eval_multi_boq.js', null, 'CLI')],
      next: [next('boq-eval-skill', 'Evaluate each supported homogeneous group; CP8 continuation pending')],
      completionEvidence: ['Group/node allocation conservation; per-group results; evidenced facility assumptions'],
      coverageLimits: ['Router currently partitions/estimates; CLI import and per-group continuation gaps remain CP8.'] }),
    capability({ capabilityId: 'rfp-sizing-synthesizer', intents: ['RFP_SIZING_TO_BOM'],
      triggers: ['Requirements without concrete SKUs'], applicability: ['Explicit sizing requirements and target product scope'],
      entrypoints: [route, entry('scripts/lib/boq/requirement_intent_resolver.js', 'resolveRequirementIntent')],
      next: [next('boq-eval-skill', 'Enough scoped requirements to form a candidate; otherwise return sizing draft')],
      completionEvidence: ['Requirement-to-candidate mapping and unresolved sizing facts'],
      coverageLimits: ['Routed sizing continuation remains CP9b; no promised rank count.'] }),
    capability({ capabilityId: 'bom-reconciliation-skill', intents: ['BOM_RECONCILIATION'],
      triggers: ['Tender versus quote comparison or single-file quote audit'], applicability: ['Two baselines for comparison; single-file audit explicitly distinct'],
      vendorScope: ['SOURCE_VENDOR_EXPLICIT'], entrypoints: [entry('scripts/lib/boq/vendor_bom_verifier.js', 'verifyVendorBOM'), entry('scripts/lib/boq/vendor_bom_verifier.js', 'auditSingleVendorBOM')],
      completionEvidence: ['Quantity/price/structural differences and pricing gaps, with baseline identity'],
      coverageLimits: ['Reconciliation does not establish hardware buildability or vendor acceptance.'] }),
    capability({ capabilityId: 'boq-remarks-reconciliation-skill', intents: ['REMARKS_RECONCILIATION'],
      triggers: ['Annotate completed reconciliation with commercial remarks'], applicability: ['Matching reconciliation baseline; original cells preserved'],
      requires: ['bom-reconciliation-skill'], entrypoints: [entry('scripts/lib/boq/commercial_remarks.js', 'appendCommercialRemarks')],
      completionEvidence: ['Auditable quantity bridges/remarks and source-row preservation'],
      coverageLimits: ['Depends on matching source fingerprints; remarks are not acceptance.'] }),
    capability({ capabilityId: 'cross-vendor-transformation-skill', intents: ['CROSS_VENDOR_TRANSFORMATION'],
      triggers: ['Requested competitor-to-HPE alternative'], applicability: ['Source requirements retained and target HPE product explicit'],
      vendorScope: ['EXPLICIT_SOURCE_TO_HPE'], entrypoints: [entry('scripts/lib/boq/cross_vendor_transformer.js', 'transformCompetitorQuote')],
      next: [next('boq-eval-skill', 'A supported target candidate exists; report parity gaps otherwise')],
      completionEvidence: ['Source-to-target requirement mapping and parity gaps'],
      coverageLimits: ['Conversion is not generic live multi-vendor evaluation; CP9d continuation pending.'] }),
    capability({ capabilityId: 'heterogeneous-tender-modernizer', intents: ['HETEROGENEOUS_TENDER_MODERNIZATION'],
      triggers: ['Mixed-domain tender or explicitly requested loose-component allocation'], applicability: ['Source row ownership, supported domains and explicit allocation basis'],
      executionMode: 'HYBRID', entrypoints: [entry('scripts/lib/boq/heterogeneous_tender_modernizer.js', 'HeterogeneousTenderModernizer')],
      next: [next('boq-eval-skill', 'Only supported owned groups; unsupported domains remain NOT_EVALUATED')],
      completionEvidence: ['Owned groups, retained spares/unparsed rows and validation gaps'],
      coverageLimits: ['Planning does not certify mixed-domain containment or every group; CP9e remains.'] }),
    capability({ capabilityId: 'ocr-quote-ingestion-skill', intents: ['OCR_QUOTE_INGESTION'],
      triggers: ['Image/scanned quote requiring OCR'], applicability: ['Actual supported input format/size and source-page provenance'],
      executionMode: 'HYBRID', vendorScope: ['SOURCE_VENDOR_EXPLICIT'],
      entrypoints: [entry('scripts/lib/ocr/ocr_service.js', 'performGeminiOcr')],
      completionEvidence: ['Extracted rows with page/source evidence and unresolved OCR ambiguities'],
      coverageLimits: ['Router descriptor does not run OCR or resume objective; CP9a pending. Ingestion is a modality, not a terminal business objective.'] }),
    capability({ capabilityId: 'catalog-intelligence-skill', intents: ['CATALOG_INTELLIGENCE'],
      triggers: ['Pricing history, lifecycle or SKU trend inquiry'], applicability: ['Exact catalog scope and observed historical dates'],
      entrypoints: [entry('scripts/lib/catalog/sku_versioning.js', 'getSkuAuditHistory'), entry('scripts/lib/catalog/sku_versioning.js', 'getHistoricalSkuPrice')],
      completionEvidence: ['Dated observations and explicit missing price/history fields'],
      coverageLimits: ['Catalog history does not prove current ordering availability.'] }),
    capability({ capabilityId: 'workload-dna-skill', intents: ['WORKLOAD_DNA'],
      triggers: ['Enterprise workload/performance architecture request'], applicability: ['Application/load requirements and disclosed assumptions'],
      entrypoints: [entry('scripts/lib/conflict/workload_dna.js', 'extractWorkloadDna')],
      next: [next('rfp-sizing-synthesizer', 'Customer requests sizing and enough load requirements are supplied')],
      completionEvidence: ['Workload profile, load assumptions and unresolved performance requirements'],
      coverageLimits: ['Profiling is not completed sizing or application certification; CP9c pending.'] }),
    capability({ capabilityId: 'value-engineering-skill', intents: ['VALUE_ENGINEERING'],
      triggers: ['Requested budget/CapEx/OpEx optimization'], applicability: ['Buildable baseline and sourced price basis; explicit requirements preserved'],
      requires: ['boq-eval-skill'], entrypoints: [entry('scripts/lib/boq/budget_optimizer.js', 'optimizeForBudget'), entry('scripts/lib/boq/deal_optimizer.js', 'evaluateDealOptimizations')],
      completionEvidence: ['Baseline/alternative evidence, price basis and changed-candidate revalidation'],
      coverageLimits: ['Legacy optimization fallbacks are not resolved by this declaration; CP10a remains.'] }),
    capability({ capabilityId: 'least-delta-combinator-skill', intents: ['LEAST_DELTA_SYNTHESIS'],
      triggers: ['Requirement-preserving minimal-change alternative request'], applicability: ['Actual diagnosed conflicts and explicit original requirements'],
      entrypoints: [entry('scripts/lib/conflict/least_delta_combinator.js', 'buildLeastDeltaCandidate')],
      completionEvidence: ['Conflict roots, mutation delta and independent candidate evaluation'],
      coverageLimits: ['Generating a candidate does not prove buildability; original intent must remain.'] }),
    capability({ capabilityId: 'workbook-generator-skill', intents: ['WORKBOOK_GENERATION'],
      triggers: ['Requested workbook/portal upload/export'], applicability: ['Requested dialect and applicable delivery authorization'],
      requires: ['output-validation-skill'], entrypoints: [entry('scripts/lib/boq/generate_boq_xlsx.js', 'generateProfessionalBOQ'), entry('scripts/lib/boq/generate_boq_xlsx.js', 'generatePartnerPortalUploadBOM')],
      completionEvidence: ['Nonempty committed artifact set, dialect checks and authorization where required'],
      coverageLimits: ['A generated spreadsheet is not live portal acceptance; existing export gates remain authoritative.'] }),
    capability({ capabilityId: 'nlm-skill', intents: ['FREEFORM_QA'],
      triggers: ['Scoped document-grounded Q&A or candidate grounding'], applicability: ['Exact notebook/product sources; cloud may be unavailable'],
      executionMode: 'AGENT_ASSISTED', entrypoints: [entry('scripts/lib/sync/nlm_solution_source_validator.js', 'validateSolutionWithEphemeralSource'), route],
      completionEvidence: ['Structured grounding verdict and native citations, or explicit unavailable state'],
      coverageLimits: ['Generic CLI manual capabilities exceed this presales mapping; citations are not live availability.'] }),
    capability({ capabilityId: 'knowledge-sync-skill', kind: 'OPERATIONAL', intents: ['KNOWLEDGE_SYNC'],
      triggers: ['Explicit/applicable knowledge sync or drift inspection'], applicability: ['Exact product sources and existing sync/recovery boundaries'],
      executionMode: 'HYBRID', entrypoints: [entry('scripts/lib/sync/knowledge_sync.js', 'inspectKnowledgeDrift'), entry('scripts/lib/sync/post_flow_sync.js', 'triggerPostFlowSyncAsync')],
      completionEvidence: ['Local/cloud sync disposition and verified readback where performed'],
      coverageLimits: ['Sync is separate from learning effectiveness and product certification.'] }),
    capability({ capabilityId: 'continuous-learning-skill', kind: 'SHARED', intents: ['CONTINUOUS_LEARNING'],
      triggers: ['Terminal reflection or explicit verified portal feedback'], applicability: ['Exact lesson identity/scope, original evidence and existing governance'],
      entrypoints: [entry('scripts/lib/feedback/feedback_loop.js', 'processPortalFeedback')],
      completionEvidence: ['Stored proposal/lesson IDs, scope and demonstrated consumer/effect when verified'],
      coverageLimits: ['Reachability is not consumption or correct behavioral effect; CP12 gaps remain.'] }),
    capability({ capabilityId: 'execution-trace-skill', kind: 'SHARED', intents: [],
      triggers: ['Any customer execution including failure/cancel'], applicability: ['Root/child correlation with actual phase/invocation observations'],
      entrypoints: [entry('scripts/lib/system/evidence_ledger.js', 'createEvidenceLedger')],
      completionEvidence: ['Actual invocation/terminal evidence and persistence outcome'],
      coverageLimits: ['Late router tracing and terminal lifecycle gaps remain CP11.'] }),
    capability({ capabilityId: 'output-validation-skill', kind: 'SHARED', intents: [],
      triggers: ['Before customer presentation or authorized artifact export'], applicability: ['Criteria for actual response/candidate profile'],
      entrypoints: [entry('scripts/lib/boq/bom_verifier.js', 'verifyPrePresentationAcceptance')],
      completionEvidence: ['Applicable criteria and response disposition, distinct from delivery authorization'],
      coverageLimits: ['Some current route profiles are UNKNOWN; CP5 remains. Requirement-discarding repair is not approved.'] }),
    capability({ capabilityId: 'adversarial-validation-skill', intents: ['ADVERSARIAL_VALIDATION'],
      triggers: ['Actual candidate scrutiny; separate engineering chaos exercise'], applicability: ['Real candidate constraints versus explicitly synthetic test population'],
      entrypoints: [entry('scripts/evaluators/adversarial_agent.js', 'evaluateAdversarialInjection'), entry('scripts/evaluators/adversarial_agent.js', 'generateAdversarialBOQ')],
      completionEvidence: ['Observed candidate checks or separately labeled synthetic test results'],
      coverageLimits: ['Synthetic chaos is not acceptance of a customer candidate; CP10b pending.'] }),
    capability({ capabilityId: 'degraded-mode-skill', kind: 'SHARED', intents: [],
      triggers: ['Stale catalog or failed/unavailable notebook'], applicability: ['Exact product freshness and cloud-health state'],
      entrypoints: [entry('scripts/lib/sync/knowledge_sync.js', 'assertNotebookHealth'), entry('scripts/lib/catalog/product_metadata_manager.js', 'getProductGenerationMetadata')],
      completionEvidence: ['Observed age/health, degradation disclosure and recovery disposition'],
      coverageLimits: ['Unavailable grounding must not erase useful local diagnosis or become false PASS.'] }),
    capability({ capabilityId: 'clic-portal-validation-skill', kind: 'SHARED', intents: [],
      triggers: ['BOQ-scoped portal investigation or final vendor acceptance'], applicability: ['Exact restored manifest, owner/selectors and current receipt'],
      executionMode: 'AGENT_ASSISTED', entrypoints: [entry('scripts/lib/boq/bom_verifier.js', 'verifyPrePresentationAcceptance', 'AGENT_PROCEDURE')],
      completionEvidence: ['Dated exact-manifest vendor receipt with owner/quantity/restoration evidence'],
      coverageLimits: ['Verifier checks evidence; it does not autonomously operate CLIC. Exploration is not acceptance.'] }),
    capability({ capabilityId: 'conditional-sku-discovery-skill', kind: 'OPERATIONAL', intents: [],
      triggers: ['Catalog conditional coverage or BOQ-scoped hidden/selector investigation'], applicability: ['Scoped base/owner/selectors; unexecuted branches disclosed'],
      executionMode: 'AGENT_ASSISTED', entrypoints: [entry('scripts/scrapers/scrape_oca_solution.js', null, 'CLI')],
      completionEvidence: ['Observed trigger/visibility provenance and restoration; acceptance separately evidenced'],
      coverageLimits: ['Hidden visibility is not mandatory compatibility; runtime selector application remains agent-assisted.'] }),
    capability({ capabilityId: 'oca-catalog-scraper', kind: 'OPERATIONAL', intents: [],
      triggers: ['Requested HPE catalog capture'], applicability: ['Live scoped OCA session and capture/promotion governance'],
      executionMode: 'CLI', entrypoints: [entry('scripts/scrapers/scrape_oca_solution.js', null, 'CLI')],
      completionEvidence: ['Scoped capture receipt, coverage and promoted deterministic/semantic artifacts'],
      coverageLimits: ['Scraping alone does not certify a solution; live portal procedure required.'] }),
    capability({ capabilityId: 'oca-portal-navigator', kind: 'OPERATIONAL', intents: [],
      triggers: ['HPE OCA navigation or session recovery'], applicability: ['Explicit target product and rendered chassis choices'],
      executionMode: 'AGENT_ASSISTED', entrypoints: [entry('scripts/lib/scraper/navigate_oca.js', 'navigateToOCAChassis')],
      completionEvidence: ['Observed exact product/session state; recovery/restoration outcome'],
      coverageLimits: ['Successful navigation is neither exhaustive capture nor candidate acceptance.'] }),
    capability({ capabilityId: 'orchestrator-workflow-skill', kind: 'OPERATIONAL', intents: [],
      triggers: ['Macro scrape/sync/evaluate/feedback lifecycle operation'], applicability: ['Explicit operational lifecycle; distinct from customer router stages'],
      executionMode: 'SERVICE', entrypoints: [entry('scripts/services/mcp_server.js', null, 'SERVICE')],
      completionEvidence: ['Actual stage receipts and local/cloud/learning dispositions'],
      coverageLimits: ['MCP service exposure is not proof that the entire macro learning lifecycle executes.'] }),
    capability({ capabilityId: 'jules-autonomous-protocol', kind: 'ENGINEERING', intents: [],
      triggers: ['Explicit Google Jules CI/CD lifecycle work'], applicability: ['Engineering session/PR review only; excluded from customer BOQ dispatch'],
      vendorScope: ['NOT_APPLICABLE'], domainScope: ['ENGINEERING'], executionMode: 'SERVICE',
      entrypoints: [entry('scripts/services/jules_task_manager.js', 'createSession')],
      completionEvidence: ['Session/review/job outcome receipts'],
      coverageLimits: ['Never a customer evaluation stage. No Jules action performed by this registry.'] }),
    capability({ capabilityId: 'design-taste-frontend', kind: 'ENGINEERING', intents: [],
      triggers: ['Requested dashboard/frontend design work'], applicability: ['Actual UI brief and existing interface behavior'],
      vendorScope: ['NOT_APPLICABLE'], domainScope: ['UI'], executionMode: 'UI',
      entrypoints: [entry('dashboard/src/main.jsx', null, 'UI')],
      completionEvidence: ['Reviewed rendered UI and interface compatibility'],
      coverageLimits: ['Engineering capability, not presales query dispatch.'] })
  ],
  internalEngineeringObservations: [{
    ownerCapabilityId: 'presales-query-router', checkpoint: 'CP7b', activation: 'DEFAULT_DISABLED_PROPOSAL',
    entrypoint: entry('scripts/lib/boq/presales_query_shadow.js', 'executeWithQueryShadow'),
    evidenceKind: 'ENGINEERING_OBSERVATION_NOT_SKILL_INVOCATION',
    reportDirectory: 'outputs/history/skill_workflow_excellence/CP7b/shadow',
    tests: ['tests/unit/test_presales_query_shadow.js'],
    limits: ['One legacy callback; proposal differences do not prove skill execution. CP11 and CP7c remain separate.']
  }],
  vendorAdapterInterface: {
    path: 'scripts/lib/contracts/vendor_adapter_contract.js', exportName: 'validateVendorAdapter',
    status: 'CONTRACT_ONLY_NO_VENDOR_MIGRATION',
    existingComponents: [
      entry('scripts/lib/scraper/vendor_scraper_adapter.js', 'BaseVendorScraperAdapter'),
      entry('scripts/lib/scraper/vendor_portal_router.js', 'routeNavigateChassis'),
      entry('scripts/lib/taxonomy/vendor_agnostic_schema.js', 'detectVendor')
    ]
  }
};

// Deep freeze prevents accidental mutation of shared nested declarations.
function freeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
}
module.exports = freeze(registry);
