'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../..'),nb='12345678-1234-1234-1234-123456789abc',log={info(){},warn(){},error(){}};
function query(exec){let now=1000,id=0;const timers=new Map(),stats={spawn:0,local:0};const mod={exports:{}};const req=s=>{if(s==='child_process')return{execFile:(...args)=>{stats.spawn++;return exec(...args);}};if(s==='fs')return{existsSync:()=>false,readFileSync:()=>JSON.stringify({notebooks:{Demo:{notebookId:nb,officialSourceIds:['official']}}})};if(s.includes('query_sanitizer'))return{sanitizeNotebookQuery:q=>q};if(s.includes('query_diagnostics'))return{postProcessNotebookResult:JSON.parse,diagnoseNotebookFailure:()=>({rootCause:'ordinary'})};if(s.includes('job_manager')||s.includes('knowledge_extractor'))return{};if(s.includes('pipeline_logger'))return log;if(s.includes('local_rag_search'))return{queryLocalKnowledgeBase(){stats.local++;return{answer:'local'};}};if(s.includes('fs_compat'))return{safeWriteJsonAtomic(){}};return require(s);};const file=path.join(root,'scripts/lib/notebook/notebook_query_utils.js');vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:mod,exports:mod.exports,require:req,__dirname:path.dirname(file),process:{env:{},platform:process.platform},Date:class extends Date{static now(){return now;}},setTimeout(fn,ms){timers.set(++id,{fn,at:now+ms});return id;},clearTimeout:i=>timers.delete(i),setInterval:()=>0,clearInterval(){}});return{run:mod.exports.executeNotebookQuery,stats,timers,advance(ms){now+=ms;for(const [i,t]of [...timers])if(t.at<=now){timers.delete(i);t.fn();}}};}
const tick=async()=>{await Promise.resolve();await Promise.resolve();};
test('pre-abort primitives/object preserve identity without spawn or fallback',async()=>{for(const reason of [null,false,NaN,{stop:1}]){const h=query(()=>a.fail()),c=new AbortController();c.abort(reason);await a.rejects(h.run(nb,'whole',{signal:c.signal}),e=>Object.is(e,reason));a.equal(h.stats.local,0);}});
test('expired-before-start no spawn/fallback',async()=>{const h=query(()=>a.fail());await a.rejects(h.run(nb,'whole',{deadlineAt:999}),e=>e.code==='NOTEBOOK_QUERY_DEADLINE_EXCEEDED');a.equal(h.stats.local,0);});
test('abort during retry backoff no next query/fallback',async()=>{const h=query((b,args,o,cb)=>cb(Error('503'))),c=new AbortController(),reason={stop:1};const p=h.run(nb,'whole',{signal:c.signal});await tick();a.equal(h.stats.spawn,1);a.equal(h.timers.size,1);c.abort(reason);await a.rejects(p,e=>e===reason);h.advance(10000);a.equal(h.stats.spawn,1);a.equal(h.stats.local,0);a.equal(h.timers.size,0);});
test('retry caps remaining budget; success unchanged',async()=>{const seen=[];const h=query((b,args,o,cb)=>{seen.push(o.timeout);seen.length===1?cb(Error('503')):cb(null,JSON.stringify({answer:'grounded',groundingVerification:'VERIFIED_GROUNDED'}),'');});const p=h.run(nb,'whole',{timeout:120000,deadlineAt:5000});await tick();h.advance(1500);const r=await p;a.deepEqual(seen,[4000,2500]);a.equal(r.attempts,2);a.equal(r.answer,'grounded');a.equal(h.stats.local,0);});
test('deadline during backoff no next query/fallback',async()=>{const h=query((b,args,o,cb)=>cb(Error('503')));const p=h.run(nb,'whole',{deadlineAt:1100});await tick();h.advance(100);await a.rejects(p,e=>e.code==='NOTEBOOK_QUERY_DEADLINE_EXCEEDED');a.equal(h.stats.spawn,1);a.equal(h.stats.local,0);});
test('ordinary query failure keeps local fallback',async()=>{const h=query((b,args,o,cb)=>cb(Error('ordinary')));a.equal((await h.run(nb,'whole')).source,'LOCAL_RAG_FALLBACK');a.equal(h.stats.local,1);});
function validator(run,onAttach=()=>{},cleanupFail=false){const stats={attach:0,detach:0,exports:0,query:0},mod={exports:{}},manifest=[{rank:1,items:[{sku:'SKU-A',quantity:2,owner:'owner-A',selectors:{ambient:27}}]},{rank:2,items:[{sku:'SKU-B',quantity:3,owner:'owner-B'}]}];const req=s=>{if(s==='fs')return{existsSync:()=>true,readFileSync:()=>JSON.stringify({notebooks:{Demo:{notebookId:nb}}})};if(s==='child_process')return{execFileSync:(b,args)=>{if(args[1]==='add'){stats.attach++;onAttach();return '{"source_id":"owned-source"}';}if(args[1]==='delete'){stats.detach++;if(cleanupFail)throw Error('cleanup');return '';}if(args[1]==='list')return '[]';a.fail(args.join(' '));}};if(s.includes('generate_boq_xlsx'))return{generateMultiRankSolutionWorkbook(){stats.exports++;},generateMultiRankSolutionCsv(){stats.exports++;}};if(s.includes('knowledge_extractor'))return{extractKnowledgeFromRagAnswer:()=>[]};if(s.includes('notebook_query_utils'))return{executeNotebookQuery:async(...args)=>{stats.query++;return run(...args);},getCachedRagResult:()=>null,setCachedRagResult(){a.fail('no certification/cache in fixture');},getNotebookConfigEntry:()=>({entry:{}}),getAuthoritativeSourceIds:()=>[]};if(s.includes('pipeline_logger'))return log;if(s.includes('solution_evidence'))return{solutionManifest:()=>manifest,solutionFingerprint:()=> 'fingerprint',candidateReviewCurrent:()=>false,canonicalJson:JSON.stringify};return require(s);};const file=path.join(root,'scripts/lib/sync/nlm_solution_source_validator.js');vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:mod,exports:mod.exports,require:req,__dirname:path.dirname(file),process:{env:{}}});return{run:mod.exports.validateSolutionWithEphemeralSource,stats};}
const evaluation={chassis:'Demo',items:[{sku:'BASE-ALL',quantity:7}],supportPolicy:{years:3},conflictGraph:{rankedSolutions:[{rank:1},{rank:2}]}};
test('whole manifest exact signal/deadline/timeout, citations and detach',async()=>{const c=new AbortController(),citations=[{source:'official'}],deadlineAt=Date.now()+10000;let seen;const h=validator(async(n,p,o)=>{seen={n,p,o};return{answer:'unverified',citations,isCloudGrounded:false};});const r=await h.run(evaluation,{signal:c.signal,timeoutMs:4500,deadlineAt,targetDir:'fixture'});a.equal(seen.o.signal,c.signal);a.equal(seen.o.timeout,4500);a.equal(seen.o.deadlineAt,deadlineAt);a.equal(seen.o.context.structuredValidation,true);for(const token of ['SKU-A','SKU-B','owner-A','owner-B','BASE-ALL','ambient'])a(seen.p.includes(token));a.equal(r.citations,citations);a.equal(r.sourceDetached,true);a.equal(h.stats.query,1);a.equal(h.stats.detach,1);});
test('post-attach abort still cleans up and retains false even cleanup fails',async()=>{const c=new AbortController();const h=validator(()=>a.fail(),()=>c.abort(false),true);await a.rejects(h.run(evaluation,{signal:c.signal}),e=>e===false);a.equal(h.stats.query,0);a.equal(h.stats.detach,1);});
test('query reject/late-success abort exact identity and cleanup',async()=>{for(const rejected of [true,false]){const c=new AbortController(),reason={stop:1};const h=validator(async()=>{c.abort(reason);if(rejected)throw reason;return{answer:'late'};});await a.rejects(h.run(evaluation,{signal:c.signal}),e=>e===reason);a.equal(h.stats.detach,1);}});
test('expired validator no mutation; unrelated failure remains unverified',async()=>{const h=validator(()=>a.fail());await a.rejects(h.run(evaluation,{deadlineAt:Date.now()-1}),e=>e.code==='NOTEBOOK_QUERY_DEADLINE_EXCEEDED');a.equal(h.stats.exports,0);a.equal(h.stats.attach,0);const other=validator(async()=>{throw Error('ordinary');});const result=await other.run(evaluation,{targetDir:'fixture'});a.equal(result.success,false);a(result.ragAnswer.includes('ordinary'));a.equal(result.doubleCheckVerdict,'DOUBLE_CHECK_REJECTED');a.equal(other.stats.detach,1);});
function caller(validate){const s=fs.readFileSync(path.join(root,'scripts/evaluators/eval_boq.js'),'utf8'),start=s.indexOf('async function executeEphemeralSourceValidation('),end=s.indexOf('// ============================================================',start);return vm.runInNewContext(s.slice(start,end)+'\nexecuteEphemeralSourceValidation',{validateSolutionWithEphemeralSource:validate,emitProgress(){},require:()=>log,Object});}
test('actual canonical stage forwards options; cancellation/deadline exact; nontrigger unchanged',async()=>{const c=new AbortController(),reason={stop:1};let seen;await caller(async(e,o)=>{seen=o;return{};})({SHEET_VALIDATION:true,signal:c.signal,timeoutMs:7300,deadlineAt:12345},{},{});a.equal(seen.signal,c.signal);a.equal(seen.timeoutMs,7300);a.equal(seen.deadlineAt,12345);c.abort(reason);await a.rejects(caller(async()=>{throw reason;})({SHEET_VALIDATION:true,signal:c.signal},{},{}),e=>e===reason);const deadline=Object.assign(Error('expired'),{code:'NOTEBOOK_QUERY_DEADLINE_EXCEEDED'});await a.rejects(caller(async()=>{throw deadline;})({SHEET_VALIDATION:true},{},{}),e=>e===deadline);a.equal(await caller(()=>a.fail())({OFFLINE_MODE:true},{},{}),null);a.equal(await caller(async()=>{throw Error('ordinary');})({SHEET_VALIDATION:true},{},{}),null);});

test('synchronous spawn failure and normal completion remove cancellation listener',async()=>{const {getEventListeners}=require('node:events');for(const failure of [true,false]){const c=new AbortController(),h=query((b,args,o,cb)=>{if(failure)throw Error('spawn failure');cb(null,JSON.stringify({answer:'ok',groundingVerification:'UNVERIFIED'}),'');});await h.run(nb,'whole',{signal:c.signal});a.equal(getEventListeners(c.signal,'abort').length,0);a.equal(h.stats.local,failure?1:0);}});
test('default absent deadline retains original retry timeout and command policy',async()=>{const seen=[];const h=query((b,args,o,cb)=>{seen.push({timeout:o.timeout,args});if(seen.length===1)cb(Error('503'));else cb(null,JSON.stringify({answer:'ok',groundingVerification:'UNVERIFIED'}),'');});const p=h.run(nb,'whole',{timeout:120000});await tick();h.advance(1500);await p;a.deepEqual(seen.map(s=>s.timeout),[120000,180000]);a(seen.every(s=>s.args.includes('--new-conversation')&&s.args.includes('--source-ids')));});

test('active abort ignores late CLI success and strict-cloud cannot turn abort into payload',async()=>{let cb;const h=query((b,args,o,callback)=>{cb=callback;}),c=new AbortController();const p=h.run(nb,'whole',{signal:c.signal,strictCloud:true});await tick();c.abort(null);await a.rejects(p,e=>e===null);cb(null,JSON.stringify({answer:'late',groundingVerification:'VERIFIED_GROUNDED'}),'');await tick();a.equal(h.stats.spawn,1);a.equal(h.stats.local,0);a.equal(h.timers.size,0);});
